### ISSUE TITLE
404 - File Not Found

### ISSUE THREAD

**Issue by ekariz** [XXPerez/codeigniter4-modular#1]
Controller or its method is not found: \Users\Controllers\Users::login

I followed all steps and still get this error. 

Any help will be much appreciated

**Comment by blazewebart** [comment]
Hello i fix it and uploaded HMVC modules to github check it, if it is still important for you

https://github.com/blazewebart/codeigniter4-hmvc

Thanks a lot, Konstantin

**Comment by XXPerez** [comment]
Solved in last refactor

**Comment by XXPerez** [comment]
Solved
